version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: ekomart_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ekomart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: ekomart_mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ekomart_technical
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
